export enum ElementType {
    // replicating IFC4 IFC Entities
    Beam = "Beam",
    Bearing = "Bearing",
    BuildingElementProxy = "BuildingElementProxy",
    BuildingSystem = "BuildingSystem",
    Chimney = "Chimney",
    Column = "Column",
    Covering = "Covering",
    CurtainWall = "CurtainWall",
    Door = "Door",
    Member = "Member",
    Plate = "Plate",
    Railing = "Railing",
    Ramp = "Ramp",
    RampFlight = "RampFlight",
    RelConnectsPathElements = "RelConnectsPathElements",
    RelCoversBldgElements = "RelCoversBldgElements",
    RelCoversSpaces = "RelCoversSpaces",
    Roof = "Roof",
    ShadingDevice = "ShadingDevice",
    Slab = "Slab",
    Stair = "Stair",
    StairFlight = "StairFlight",
    Wall = "Wall",
    WallStandardCase = "WallStandardCase",
    Window = "Window",
  }
  